Pan

In [119]:
import numpy as np
import pandas as pd

In [120]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [121]:
print(data.values)

[0.25 0.5  0.75 1.  ]


In [122]:
print(type(data.values))

<class 'numpy.ndarray'>


In [123]:
print(data.index)

RangeIndex(start=0, stop=4, step=1)


In [124]:
print(type(data.index))

<class 'pandas.core.indexes.range.RangeIndex'>


In [125]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64


In [126]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=["a", "b", "c", "d"])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [127]:
print(type(data.index[0]))

<class 'str'>


In [128]:
print(data["a"])
print("a" in data)
print("a1" in data)
print(list(data.items()))

0.25
True
False
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]


In [129]:
data["a"] = 99
data["qwr"] = 999
print(data)

a       99.00
b        0.50
c        0.75
d        1.00
qwr    999.00
dtype: float64


In [130]:
print(data[2:4])
print(data["c":"d"])

c    0.75
d    1.00
dtype: float64
c    0.75
d    1.00
dtype: float64


In [131]:
print(data["b":"d"]) #внимательно

b    0.50
c    0.75
d    1.00
dtype: float64


In [132]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 10, 7, "d"])
print(data)

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64


In [133]:
print(type(data.index[0]))
print(type(data.index[3]))

<class 'int'>
<class 'str'>


In [134]:
print(data[10:"d"])

10    0.50
7     0.75
d     1.00
dtype: float64


In [135]:
dict = {
    'A':10,
    'B':20,
    'C':30,
    'D':40,
    'E':50,
}
data_dict = pd.Series(dict)
print(data_dict)
print(data_dict['B':'D'])



A    10
B    20
C    30
D    40
E    50
dtype: int64
B    20
C    30
D    40
dtype: int64


In [136]:
data = pd.Series(5, index=[10,20,30])
print(data)

10    5
20    5
30    5
dtype: int64


In [137]:
data = pd.Series(dict, index=["A", "D"])
print(data)

A    10
D    40
dtype: int64


чтобы создать Series можно использовать списки, слвоари или повторение одного объёкта

In [152]:
dict1 = {
    'A':10,
    'B':20,
    'C':30,
    'D':40,
    'E':50,
}
data_dict1 = pd.Series(dict1)

dict2 = {
    'A':11,
    'B':21,
    'C':31,
    'D':41,
    'E':51,
}
data_dict2 = pd.Series(dict2)


In [139]:
data_frame = pd.DataFrame({"dict_01":data_dict1, "dict_02":data_dict2})
print(data_frame)

   dict_01  dict_02
A       10       11
B       20       21
C       30       31
D       40       41
E       50       51


In [140]:
print(data_frame.values)
print(type(data_frame.values))

[[10 11]
 [20 21]
 [30 31]
 [40 41]
 [50 51]]
<class 'numpy.ndarray'>


In [141]:
print(data_frame.columns)
print(type(data_frame.columns))

Index(['dict_01', 'dict_02'], dtype='object')
<class 'pandas.core.indexes.base.Index'>


In [142]:
print(data_frame.index)
print(type(data_frame.index))

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
<class 'pandas.core.indexes.base.Index'>


In [143]:
print(data_frame["dict_01"])
print(data_frame["dict_02"])

A    10
B    20
C    30
D    40
E    50
Name: dict_01, dtype: int64
A    11
B    21
C    31
D    41
E    51
Name: dict_02, dtype: int64


In [144]:
print(type(data_frame["dict_01"]))

<class 'pandas.core.series.Series'>


In [145]:
df = pd.DataFrame({"dict_01":data_dict1})
print(df)
print(df.values)  # у этого объекта размерность вектор столбца,
#а не просто массив без рахмерности,как просто массив numpy

   dict_01
A       10
B       20
C       30
D       40
E       50
[[10]
 [20]
 [30]
 [40]
 [50]]


In [146]:
df = pd.DataFrame(data_dict1, columns=["rrr"])
print(df)
print(df.values)

   rrr
A   10
B   20
C   30
D   40
E   50
[[10]
 [20]
 [30]
 [40]
 [50]]


In [147]:
print(pd.DataFrame([{"a":i, "b":2*i} for i in range(4)]))

   a  b
0  0  0
1  1  2
2  2  4
3  3  6


In [148]:
print(pd.DataFrame(np.zeros(3)))

     0
0  0.0
1  0.0
2  0.0


Index - спобос сослатсья (reference) на данные в Series или в DataFrame

In [149]:
index = pd.Index([2, 5, 3, 6, 71])
print(index)
print(type(index))
print(index[1])
print(index[::2])

Index([2, 5, 3, 6, 71], dtype='int64')
<class 'pandas.core.indexes.base.Index'>
5
Index([2, 3, 71], dtype='int64')


In [150]:
#index[1] = 123 - индексы менять нельзя

In [151]:
index1 = pd.Index([2, 5, 3, 6, 71])
index2 = pd.Index([1, 2, 51, 71, 41])
print(index1.intersection(index2))
print(index1.union(index2))
print(index1.symmetric_difference(index2))

Index([2, 71], dtype='int64')
Index([1, 2, 3, 5, 6, 41, 51, 71], dtype='int64')
Index([1, 3, 5, 6, 41, 51], dtype='int64')


NumPy: \
индекцсация \
срезы arr[:, 1:4] \
маскирование arr[arr > 5] \
arr[0, [1,5]] arr[:, [1,5]] \



Pandas: \
индексация \
маскирование


In [154]:
dict1 = {
    'A':10,
    'B':20,
    'C':30,
    'D':40,
    'E':50,
}
data_dict1 = pd.Series(dict1)

dict2 = {
    'A':11,
    'B':21,
    'C':31,
    'D':41,
    'E':51,
}
data_dict2 = pd.Series(dict2)

df = pd.DataFrame({"dict_01":data_dict1, "dict_02":data_dict2})
print(df)

   dict_01  dict_02
A       10       11
B       20       21
C       30       31
D       40       41
E       50       51


In [156]:
print(df["dict_01"])
print(df.dict_01)

A    10
B    20
C    30
D    40
E    50
Name: dict_01, dtype: int64
A    10
B    20
C    30
D    40
E    50
Name: dict_01, dtype: int64


In [157]:
df["new"] = df["dict_01"]
print(df)

   dict_01  dict_02  new
A       10       11   10
B       20       21   20
C       30       31   30
D       40       41   40
E       50       51   50


In [158]:
df["new"] = df["dict_01"] / df["dict_02"]
print(df)

   dict_01  dict_02       new
A       10       11  0.909091
B       20       21  0.952381
C       30       31  0.967742
D       40       41  0.975610
E       50       51  0.980392


In [160]:
print(df.values)
print(df["dict_01"]) # столбец
print(df.values[0]) # строка

[[10.         11.          0.90909091]
 [20.         21.          0.95238095]
 [30.         31.          0.96774194]
 [40.         41.          0.97560976]
 [50.         51.          0.98039216]]
A    10
B    20
C    30
D    40
E    50
Name: dict_01, dtype: int64
[10.         11.          0.90909091]


In [174]:
print(df.loc["A":"C", :"dict_02"])

   dict_01  dict_02
A       10       11
B       20       21
C       30       31


In [176]:
print(df.iloc[0:3, :2])

   dict_01  dict_02
A       10       11
B       20       21
C       30       31


In [179]:
print(df.loc[df.dict_02 > 30, ["dict_01", "new"]])

   dict_01       new
C       30  0.967742
D       40  0.975610
E       50  0.980392


In [181]:
df.loc[df.dict_02 > 30, ["dict_01", "new"]] = 36
print(df)

   dict_01  dict_02        new
A       10       11   0.909091
B       20       21   0.952381
C       36       31  36.000000
D       36       41  36.000000
E       36       51  36.000000


In [182]:
rng = np.random.default_rng(1)
s = pd.Series(rng.integers(0, 10, 6))
print(s)

0    4
1    5
2    7
3    9
4    0
5    1
dtype: int64


In [183]:
print(np.exp(s))

0      54.598150
1     148.413159
2    1096.633158
3    8103.083928
4       1.000000
5       2.718282
dtype: float64


In [185]:
df = pd.DataFrame(rng.integers(0, 10, (3,4)), columns=['A', 'B', 'C', 'D'])
print(df)

   A  B  C  D
0  0  0  8  7
1  8  5  8  3
2  4  7  1  3


In [186]:
print(np.sin(df * 4))

          A         B         C         D
0  0.000000  0.000000  0.551427  0.270906
1  0.551427  0.912945  0.551427 -0.536573
2 -0.287903  0.270906 -0.756802 -0.536573


не смотря на то, что numpy ничего не знает про pandas, операции делать можно и индексы сохраняются

In [192]:
dict1 = {
    'A':10,
    'B':20,
    'C':30,
    'D':40,
    'E':50,
    'F':60,
}
data_dict1 = pd.Series(dict1)

dict2 = {
    'A':11,
    'B':21,
    'C':31,
    'D':41,
    'E':51,
    'H':71
}
data_dict2 = pd.Series(dict2)


df = pd.DataFrame({"dict_01":data_dict1, "dict_02":data_dict2})
print(df)

print(data_dict1 + data_dict2)
print(np.add(data_dict1, data_dict2))
print(data_dict1.add(data_dict2, fill_value = 5))

   dict_01  dict_02
A     10.0     11.0
B     20.0     21.0
C     30.0     31.0
D     40.0     41.0
E     50.0     51.0
F     60.0      NaN
H      NaN     71.0
A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
F      NaN
H      NaN
dtype: float64
A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
F      NaN
H      NaN
dtype: float64
A     21.0
B     41.0
C     61.0
D     81.0
E    101.0
F     65.0
H     76.0
dtype: float64


In [200]:
df1 = pd.DataFrame({"dict_10":data_dict1, "dict_02":data_dict2})
print(df1)

print(df + df1)

print(df.add(df1, fill_value=555))
print(df.add(df1, fill_value=df.values.sum()))

   dict_10  dict_02
A     10.0     11.0
B     20.0     21.0
C     30.0     31.0
D     40.0     41.0
E     50.0     51.0
F     60.0      NaN
H      NaN     71.0
   dict_01  dict_02  dict_10
A      NaN     22.0      NaN
B      NaN     42.0      NaN
C      NaN     62.0      NaN
D      NaN     82.0      NaN
E      NaN    102.0      NaN
F      NaN      NaN      NaN
H      NaN    142.0      NaN
   dict_01  dict_02  dict_10
A    565.0     22.0    565.0
B    575.0     42.0    575.0
C    585.0     62.0    585.0
D    595.0     82.0    595.0
E    605.0    102.0    605.0
F    615.0      NaN    615.0
H      NaN    142.0      NaN
   dict_01  dict_02  dict_10
A      NaN     22.0      NaN
B      NaN     42.0      NaN
C      NaN     62.0      NaN
D      NaN     82.0      NaN
E      NaN    102.0      NaN
F      NaN      NaN      NaN
H      NaN    142.0      NaN


In [201]:
A = rng.integers(10, size=(3,4))
print(A)

[[1 4 9 1]
 [3 4 9 2]
 [5 2 0 7]]


In [202]:
print(A[0])
print(A - A[0])

[1 4 9 1]
[[ 0  0  0  0]
 [ 2  0  0  1]
 [ 4 -2 -9  6]]


In [205]:
df = pd.DataFrame(A, columns=["A", "B", "C", "D"])
print(df)
print(df - df.iloc[0])

   A  B  C  D
0  1  4  9  1
1  3  4  9  2
2  5  2  0  7
   A  B  C  D
0  0  0  0  0
1  2  0  0  1
2  4 -2 -9  6


In [210]:
print(df.subtract(df["A"], axis = 0)) 

   A  B  C  D
0  0  3  8  0
1  0  1  6 -1
2  0 -3 -5  2
