In [21]:
import numpy as np
import pandas as pd

отсутвтвующие данныее

In [6]:
a = np.nan
a = -99999

In [7]:
a = None
print(type(a))

<class 'NoneType'>


In [10]:
a = np.array([1, 2, 3])
b = np.array([1, None, 3])
print(a.sum())


6


In [11]:
print(b.sum())

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [14]:
c = np.array([1, np.nan, 3]) #nan - дейцствительное число
print(c)
print(c.sum())
print(1 + np.nan)

[ 1. nan  3.]
nan
nan


In [18]:
print(np.sum(c))
print(np.nansum(c)) #игнорирует nan

nan
4.0


In [22]:
x = pd.Series([1, 2, 3, 4, 5], dtype=int)
print(x)
x[0] = None
x[1] = np.nan
print(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    NaN
1    NaN
2    3.0
3    4.0
4    5.0
dtype: float64


In [25]:
x = pd.Series(["1", "2", "3", "4", "5"])
print(x)
x[0] = None
x[1] = np.nan
print(x)

0    1
1    2
2    3
3    4
4    5
dtype: object
0    None
1     NaN
2       3
3       4
4       5
dtype: object


In [26]:
x = pd.Series([True, False, False, True])
print(x)
x[0] = None
x[1] = np.nan
print(x)

0     True
1    False
2    False
3     True
dtype: bool
0      NaN
1      NaN
2    False
3     True
dtype: object


C:\Users\mikha\AppData\Local\Temp\ipykernel_22908\3457418906.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  x[0] = None


In [27]:
x = pd.Series([1, np.nan, None, 5])
print(x)

0    1.0
1    NaN
2    NaN
3    5.0
dtype: float64


In [28]:
x = pd.Series([1, np.nan, None, 5, pd.NA])
print(x)

0       1
1     NaN
2    None
3       5
4    <NA>
dtype: object


In [29]:
x = pd.Series([1, np.nan, None, 5, pd.NA], dtype="Int32")
print(x)

0       1
1    <NA>
2    <NA>
3       5
4    <NA>
dtype: Int32


In [30]:
x = pd.Series([1, np.nan, None, 5, "hello"])
print(x)

0        1
1      NaN
2     None
3        5
4    hello
dtype: object


In [33]:
print(x.isnull())
print(x.notnull())
print(x[x.isnull()])
print(x[x.notnull()])
print(x.dropna())

0    False
1     True
2     True
3    False
4    False
dtype: bool
0     True
1    False
2    False
3     True
4     True
dtype: bool
1     NaN
2    None
dtype: object
0        1
3        5
4    hello
dtype: object
0        1
3        5
4    hello
dtype: object


In [35]:
x = pd.DataFrame([[1, np.nan, None], [1, 2, 3], [2, np.nan, 3]])
print(x)

   0    1    2
0  1  NaN  NaN
1  1  2.0  3.0
2  2  NaN  3.0


In [41]:
print(x.dropna())
print(x.dropna(axis=0))
print(x.dropna(axis=1))
x = pd.DataFrame([[None, np.nan, None], [1, 2, 3], [2, np.nan, 3]])
print(x.dropna(axis=0, how='all'))

   0    1    2
1  1  2.0  3.0
   0    1    2
1  1  2.0  3.0
   0
0  1
1  1
2  2
     0    1    2
1  1.0  2.0  3.0
2  2.0  NaN  3.0


In [ ]:
x = pd.DataFrame([[None, np.nan, None], [1, 2, 3], [2, np.nan, 3]])
print(x.dropna(axis=0, thresh= )) #должно быть минимум N не пустых значений

In [44]:
x = pd.DataFrame([None, 4, np.nan, 5, None, 1, 2, 3], dtype = "Int32")
print(x)
print(x.fillna(-4))
print(x.ffill()) # заполнение предыдущим
print(x.bfill()) # заполнение следущим


      0
0  <NA>
1     4
2  <NA>
3     5
4  <NA>
5     1
6     2
7     3
    0
0  -4
1   4
2  -4
3   5
4  -4
5   1
6   2
7   3
      0
0  <NA>
1     4
2     4
3     5
4     5
5     1
6     2
7     3
   0
0  4
1  4
2  5
3  5
4  1
5  1
6  2
7  3


In [45]:
x = pd.DataFrame([[None, np.nan, None], [1, 2, 3], [2, np.nan, 3]])
print(x.ffill(axis=1))
print(x.bfill(axis=1))
print(x.ffill(axis=0))
print(x.bfill(axis=0)) 

     0    1    2
0  NaN  NaN  NaN
1  1.0  2.0  3.0
2  2.0  2.0  3.0
     0    1    2
0  NaN  NaN  NaN
1  1.0  2.0  3.0
2  2.0  3.0  3.0
     0    1    2
0  NaN  NaN  NaN
1  1.0  2.0  3.0
2  2.0  2.0  3.0
     0    1    2
0  1.0  2.0  3.0
1  1.0  2.0  3.0
2  2.0  NaN  3.0


Иерархическая индексация

In [48]:
index = [("A1", 2025), ("A2", 2024), ("A3", 2023), ("A4", 2022),("A5", 2021), ("A6", 2020)]
data = [1, 2, 3, 4, 5, 6]
s= pd.Series(data, index = index)
print(s)

(A1, 2025)    1
(A2, 2024)    2
(A3, 2023)    3
(A4, 2022)    4
(A5, 2021)    5
(A6, 2020)    6
dtype: int64


In [49]:
print(s[[0,2,4]])
print(s[[i for i in s.index if i[1] == 2025]])

(A1, 2025)    1
(A3, 2023)    3
(A5, 2021)    5
dtype: int64
(A1, 2025)    1
dtype: int64


C:\Users\mikha\AppData\Local\Temp\ipykernel_22908\1993222402.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[[0,2,4]])


In [51]:
mi = pd.MultiIndex.from_tuples(index)
print(mi)

MultiIndex([('A1', 2025),
            ('A2', 2024),
            ('A3', 2023),
            ('A4', 2022),
            ('A5', 2021),
            ('A6', 2020)],
           )


In [52]:
s = s.reindex(mi)
print(s)

A1  2025    1
A2  2024    2
A3  2023    3
A4  2022    4
A5  2021    5
A6  2020    6
dtype: int64


In [53]:
s1 = pd.Series(data, index = mi)
print(s1)
print(s['A1', :])

A1  2025    1
A2  2024    2
A3  2023    3
A4  2022    4
A5  2021    5
A6  2020    6
dtype: int64
2025    1
dtype: int64


In [ ]:
df = s.unstack()
print(df)

In [ ]:
print(df.stack())

одномерный Series может хранить данные с большим числом измерений

In [58]:
index = [("A1", 2025, 1), 
         ("A2", 2024, 2),
         ("A3", 2023, 3),
         ("A4", 2022, 4),
         ("A5", 2021, 5),
         ("A6", 2020, 6),
         ("A1", 2025, 7), 
         ("A2", 2024, 8),
         ("A3", 2023, 9),
         ("A4", 2022, 10),
         ("A5", 2021, 11),
         ("A6", 2020, 12)]
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
s= pd.Series(data, index = index)
print(s)
mi = pd.MultiIndex.from_tuples(index)
s = s.reindex(mi)
print(s)
print(s[:, 2025, 1])

(A1, 2025, 1)      1
(A2, 2024, 2)      2
(A3, 2023, 3)      3
(A4, 2022, 4)      4
(A5, 2021, 5)      5
(A6, 2020, 6)      6
(A1, 2025, 7)      7
(A2, 2024, 8)      8
(A3, 2023, 9)      9
(A4, 2022, 10)    10
(A5, 2021, 11)    11
(A6, 2020, 12)    12
dtype: int64
A1  2025  1      1
A2  2024  2      2
A3  2023  3      3
A4  2022  4      4
A5  2021  5      5
A6  2020  6      6
A1  2025  7      7
A2  2024  8      8
A3  2023  9      9
A4  2022  10    10
A5  2021  11    11
A6  2020  12    12
dtype: int64
A1    1
dtype: int64


In [59]:
df = s.unstack()
print(df)

          1    2    3    4    5    6    7    8    9     10    11    12
A1 2025  1.0  NaN  NaN  NaN  NaN  NaN  7.0  NaN  NaN   NaN   NaN   NaN
A2 2024  NaN  2.0  NaN  NaN  NaN  NaN  NaN  8.0  NaN   NaN   NaN   NaN
A3 2023  NaN  NaN  3.0  NaN  NaN  NaN  NaN  NaN  9.0   NaN   NaN   NaN
A4 2022  NaN  NaN  NaN  4.0  NaN  NaN  NaN  NaN  NaN  10.0   NaN   NaN
A5 2021  NaN  NaN  NaN  NaN  5.0  NaN  NaN  NaN  NaN   NaN  11.0   NaN
A6 2020  NaN  NaN  NaN  NaN  NaN  6.0  NaN  NaN  NaN   NaN   NaN  12.0


In [61]:
df1 = pd.DataFrame(
    {"jan": s[:, :, 1],
     "feb": s[:, :, 2],
     "mar": s[:, :, 1] + s[:, :, 2]
    }
)
print(df1)

         jan  feb  mar
A1 2025  1.0  NaN  NaN
A2 2024  NaN  2.0  NaN


In [63]:
print(df1["mar"])
print(df1.loc["A1"])
print(df1.loc["A1", "feb"])

A1  2025   NaN
A2  2024   NaN
Name: mar, dtype: float64
      jan  feb  mar
2025  1.0  NaN  NaN
2025   NaN
Name: feb, dtype: float64


In [64]:
print(df1.loc[["A1", "A2"], ["feb", "jan"]])

         feb  jan
A1 2025  NaN  1.0
A2 2024  2.0  NaN


In [71]:
rng = np.random.default_rng(1)
df = pd.DataFrame(
    rng.random((4, 2)),
    index=[["A1", "A1", "A2", "A2"], [2025, 2026, 2025, 2026]],
    columns=["jan", "feb"]
)
print(df)

              jan       feb
A1 2025  0.511822  0.950464
   2026  0.144160  0.948649
A2 2025  0.311831  0.423326
   2026  0.827703  0.409199


In [72]:
index = {("A1", 2025, 1): 1, 
         ("A2", 2024, 2): 2,
         ("A3", 2023, 3): 3,
         ("A4", 2022, 4): 4,
         ("A5", 2021, 5): 5,
         ("A6", 2020, 6): 6,
         ("A1", 2025, 7): 7, 
         ("A2", 2024, 8): 8,
         ("A3", 2023, 9): 9,
         ("A4", 2022, 10): 10,
         ("A5", 2021, 11): 11,
         ("A6", 2020, 12): 12,
         }
s = pd.Series(data)
print(s)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64


In [74]:
index = [("A1", 2025, 1), 
         ("A2", 2024, 2),
         ("A3", 2023, 3),
         ("A4", 2022, 4),
         ("A5", 2021, 5),
         ("A6", 2020, 6),
         ("A1", 2025, 7), 
         ("A2", 2024, 8),
         ("A3", 2023, 9),
         ("A4", 2022, 10),
         ("A5", 2021, 11),
         ("A6", 2020, 12)]
mi = pd.MultiIndex.from_arrays([["A1", "A1", "A2", "A2"], [2025, 2026, 2025, 2026]])
print(mi)

mi = pd.MultiIndex.from_arrays([["A1", "A1", "A2", "A2"], [2025, 2026, 2025, 2026]])
print(mi)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           )
MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           )


In [77]:
mi = pd.MultiIndex(
    levels=[["A1", "A2"], [2025, 2026]],
    codes =[[0,0,1,1], [0,1,0,1]]
)
print(mi)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           )


In [78]:
mi = pd.MultiIndex(
    levels=[["A1", "A2"], [2025, 2026]],
    codes =[[0,0,1], [0,1,0]]
)
print(mi)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025)],
           )


In [79]:
df = pd.DataFrame(
    rng.random((4, 2)),
    index=[["A1", "A1", "A2", "A2"], [2025, 2026, 2025, 2026]],
    columns=["jan", "feb"]
)
df.index.names = ["property", "year"]
print(df)

                    jan       feb
property year                    
A1       2025  0.549594  0.027559
         2026  0.753513  0.538143
A2       2025  0.329732  0.788429
         2026  0.303195  0.453498


In [87]:
mi1 = pd.MultiIndex.from_arrays([["A1", "A1", "A2", "A2"], [2025, 2026, 2025, 2026]], names = ["property", "year"])
print(mi)

MultiIndex([('A1', 2025),
            ('A1', 2026),
            ('A2', 2025),
            ('A2', 2026)],
           names=['property', 'year'])


In [88]:
mi2 = pd.MultiIndex.from_product([["B1", "B2", "B3"], ["jan", "feb"]], names = ["shop", "month"])
print(mi2)

MultiIndex([('B1', 'jan'),
            ('B1', 'feb'),
            ('B2', 'jan'),
            ('B2', 'feb'),
            ('B3', 'jan'),
            ('B3', 'feb')],
           names=['shop', 'month'])


In [89]:
data = rng.random((4, 6))
print(data)

[[0.64132817 0.85263284 0.59294102 0.26009745 0.83988152 0.50949588]
 [0.51088888 0.75303021 0.14792204 0.81962672 0.68328691 0.78709694]
 [0.19161626 0.80236416 0.19132393 0.08155262 0.85522697 0.8612835 ]
 [0.8765371  0.47190972 0.27404839 0.00709183 0.6457209  0.71990938]]


In [90]:
df = pd.DataFrame(data, index=mi1, columns=mi2)
print(df)

shop                 B1                  B2                  B3          
month               jan       feb       jan       feb       jan       feb
property year                                                            
A1       2025  0.641328  0.852633  0.592941  0.260097  0.839882  0.509496
         2026  0.510889  0.753030  0.147922  0.819627  0.683287  0.787097
A2       2025  0.191616  0.802364  0.191324  0.081553  0.855227  0.861283
         2026  0.876537  0.471910  0.274048  0.007092  0.645721  0.719909
